USE WAREHOUSE COMPUTE_WH;

--  Remove old table (if it exists)
DROP TABLE IF EXISTS MY_DATABASE.MY_SCHEMA.STOCK_HISTORY;

--  Create new table
CREATE OR REPLACE TABLE MY_DATABASE.MY_SCHEMA.STOCK_HISTORY (  
    symbol STRING,  
    datetime TIMESTAMP,  
    open FLOAT,  
    close FLOAT,  
    high FLOAT,  
    low FLOAT,  MY_DATABASE.MY_SCHEMA.FINAL_STOCK_TABLE
    volume FLOAT,  
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    end_date TIMESTAMP,  
    is_current BOOLEAN DEFAULT TRUE  
);

---Check If STAGING Tables Have Data

SELECT COUNT(*) FROM MY_DATABASE.MY_SCHEMA.AAPL_STAGING;
SELECT COUNT(*) FROM MY_DATABASE.MY_SCHEMA.TSLA_STAGING;


--Truncate STAGING (To Remove Any Old Data)


TRUNCATE TABLE MY_DATABASE.MY_SCHEMA.AAPL_STAGING;
TRUNCATE TABLE MY_DATABASE.MY_SCHEMA.TSLA_STAGING;

---check if dag 


SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'fetch_stock_data_to_snowflake'
ORDER BY SCHEDULED_TIME DESC
LIMIT 5;

SHOW TASKS;

---Verify API Data in STAGING After Airflow Execution

SELECT * FROM MY_DATABASE.MY_SCHEMA.TSLA_STAGING
ORDER BY datetime DESC
LIMIT 5;

DESC TABLE MY_DATABASE.MY_SCHEMA.TSLA_STAGING;



